[project]
name = "anibridge-docs"
version = "0.1.0"
description = "Documentation for the AniBridge project."
license = "MIT"
license-files = ["LICENSE"]
readme = "README.md"
requires-python = ">=3.14"

authors = [
  { name = "Elias Benbourenane", email = "eliasbenbourenane@gmail.com" },
]
maintainers = [
  { name = "Elias Benbourenane", email = "eliasbenbourenane@gmail.com" },
]

classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.14",
  "Operating System :: OS Independent",
]

dependencies = ["anibridge", "mkdocstrings-python>=2.0.3", "zensical>=0.0.30"]

[tool.uv.sources]
anibridge = { git = "https://github.com/anibridge/anibridge.git", rev = "v2.1.3" }
